"use client";

import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { channelData } from "@/lib/data";
import CardWrapper from "@/components/CardWrapper";

function CustomTooltip({ active, payload }: { active?: boolean; payload?: { name: string; value: number; payload: { color: string } }[] }) {
  if (!active || !payload?.length) return null;
  const d = payload[0];
  return (
    <div
      style={{
        background: "var(--card)",
        border: "1px solid var(--line)",
        borderRadius: 8,
        padding: "6px 10px",
        fontFamily: "var(--font-geist-mono)",
        fontSize: 11,
        color: "var(--ink)",
        boxShadow: "var(--tooltip-shadow)",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 2 }}>
        <span style={{ width: 8, height: 8, borderRadius: "50%", background: d.payload.color, display: "inline-block" }} />
        <span style={{ color: "var(--muted)" }}>{d.name}</span>
      </div>
      <div style={{ fontWeight: 500 }}>{d.value}% of new accounts</div>
    </div>
  );
}

export default function ChannelMixCard() {
  return (
    <CardWrapper
      title="Metric name"
      description="One line metric description or function"
      insight="Insight is Autogenerated"
      explanationTitle="Explanation of movement"
      explanationBody="Explains the movement of the graph and pulls out values, no judgment is exerted here."
    >
      <div style={{ width: "100%", display: "flex", flexDirection: "column", alignItems: "center" }}>
        <ResponsiveContainer width="100%" height={200}>
          <PieChart>
            <Pie
              data={channelData}
              cx="50%"
              cy="50%"
              outerRadius={88}
              dataKey="value"
              strokeWidth={1.5}
              stroke="var(--card)"
            >
              {channelData.map((entry) => (
                <Cell
                  key={entry.name}
                  fill={entry.color}
                  stroke="var(--card)"
                  strokeWidth={1.5}
                />
              ))}
            </Pie>
            <Tooltip content={<CustomTooltip />} />
          </PieChart>
        </ResponsiveContainer>
      </div>
    </CardWrapper>
  );
}
