"use client";

import {
  RadarChart,
  Radar,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { radarData } from "@/lib/data";
import CardWrapper from "@/components/CardWrapper";

function CustomTooltip({ active, payload, label }: { active?: boolean; payload?: { value: number }[]; label?: string }) {
  if (!active || !payload?.length) return null;
  return (
    <div
      style={{
        background: "var(--card)",
        border: "1px solid var(--line)",
        borderRadius: 8,
        padding: "6px 10px",
        fontFamily: "var(--font-geist-mono)",
        fontSize: 11,
        color: "var(--ink)",
        boxShadow: "var(--tooltip-shadow)",
      }}
    >
      <div style={{ color: "var(--muted)", marginBottom: 2 }}>{label}</div>
      <div style={{ fontWeight: 500 }}>{payload[0].value}</div>
    </div>
  );
}

type Anchor = "middle" | "start" | "end";
type Baseline = "auto" | "hanging" | "middle";
const labelConfig: Record<string, { ox: number; oy: number; anchor: Anchor; baseline: Baseline }> = {
  "Reach":        { ox:  0,  oy: 1, anchor: "middle", baseline: "auto"    },
  "Engagement":   { ox:  1, oy: 6,  anchor: "start",  baseline: "auto"    },
  "Conversion":   { ox:  0, oy:  -9,  anchor: "start",  baseline: "hanging" },
  "Retention":    { ox:  0,  oy:  -4, anchor: "middle", baseline: "hanging" },
  "Viral Coeff.": { ox: 5, oy:  -10,  anchor: "end",    baseline: "hanging" },
  "AUM Growth":   { ox: 1, oy: 6,  anchor: "end",    baseline: "auto"    },
};

function axisLabel({ x, y, payload }: { x: number; y: number; payload: { value: string } }) {
  const cfg = labelConfig[payload.value] ?? { ox: 0, oy: 0, anchor: "middle", baseline: "middle" };
  return (
    <text
      x={x + cfg.ox}
      y={y + cfg.oy}
      textAnchor={cfg.anchor}
      fill="var(--muted-2)"
      style={{ fontFamily: "var(--font-geist-mono)", fontSize: 9 }}
      dominantBaseline={cfg.baseline}
    >
      {payload.value}
    </text>
  );
}

export default function PerformanceCard() {
  return (
    <CardWrapper
      title="Metric name"
      description="One line metric description or function"
      insight="Insight is Autogenerated"
      explanationTitle="Explanation of movement"
      explanationBody="Explains the movement of the graph and pulls out values, no judgment is exerted here."
    >
      <div style={{ width: "100%", transform: "scaleX(1.1)", transformOrigin: "center" }}>
      <ResponsiveContainer width="100%" height={220}>
        <RadarChart data={radarData} margin={{ top: 14, right: 38, bottom: 14, left: 38 }} outerRadius="88%">
          <PolarGrid
            stroke="var(--line)"
            strokeWidth={0.8}
            gridType="polygon"
          />
          <PolarAngleAxis dataKey="metric" tick={axisLabel as never} tickLine={false} />
          <PolarRadiusAxis domain={[0, 100]} tick={false} axisLine={false} />
          <Radar
            name="current"
            dataKey="current"
            stroke="#9b8ff9"
            strokeWidth={1.5}
            fill="#9b8ff9"
            fillOpacity={0.28}
            dot={{ r: 3, fill: "#9b8ff9", strokeWidth: 1.5, stroke: "var(--card)" }}
            isAnimationActive={false}
          />
          <Tooltip content={<CustomTooltip />} />
        </RadarChart>
      </ResponsiveContainer>
      </div>
    </CardWrapper>
  );
}
