"use client";

import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  ReferenceLine,
} from "recharts";
import { useState } from "react";
import { revenueData, formatMoney } from "@/lib/data";
import CardWrapper from "@/components/CardWrapper";

const LINE1 = "#d4547a";
const LINE2 = "#6b9e6b";

function CustomTooltip({ active, payload, label }: { active?: boolean; payload?: { value: number; name: string }[]; label?: string }) {
  if (!active || !payload?.length) return null;
  return (
    <div
      style={{
        background: "var(--card)",
        border: "1px solid var(--line)",
        borderRadius: 8,
        padding: "6px 10px",
        fontFamily: "var(--font-geist-mono)",
        fontSize: 11,
        color: "var(--ink)",
        boxShadow: "var(--tooltip-shadow)",
      }}
    >
      {label && <div style={{ color: "var(--muted)", marginBottom: 4 }}>{label} 2025–26</div>}
      {payload.map((p) => (
        <div key={p.name} style={{ display: "flex", justifyContent: "space-between", gap: 12 }}>
          <span style={{ color: p.name === "revenue" ? LINE1 : LINE2 }}>
            {p.name === "revenue" ? "Legend 01" : "Legend 02"}
          </span>
          <span style={{ fontWeight: 500 }}>{formatMoney(p.value)}</span>
        </div>
      ))}
    </div>
  );
}

function yTick({ x, y, payload }: { x: number; y: number; payload: { value: number } }) {
  return (
    <text
      x={x - 4}
      y={y + 3}
      textAnchor="end"
      fill="var(--muted-2)"
      style={{ fontFamily: "var(--font-geist-mono)", fontSize: 9.5 }}
    >
      {formatMoney(payload.value)}
    </text>
  );
}

export default function RevenueCard() {
  const [tooltipActive, setTooltipActive] = useState(false);
  const legend = (
    <div
      style={{
        display: "flex",
        gap: 20,
        fontFamily: "var(--font-geist-mono)",
        fontSize: 11,
        color: "var(--muted)",
        marginBottom: 6,
      }}
    >
      <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
        <span style={{ width: 14, height: 2, background: LINE1, display: "inline-block", borderRadius: 2 }} />
        Legend 01
      </span>
      <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
        <span style={{ width: 14, height: 2, background: LINE2, display: "inline-block", borderRadius: 2 }} />
        Legend 02
      </span>
    </div>
  );

  return (
    <CardWrapper
      title="Metric name"
      legend={legend}
      insight="Insight is Autogenerated"
      explanationTitle="Explanation of movement"
      explanationBody="Explains the movement of the graph and pulls out values, no judgment is exerted here."
    >
      <ResponsiveContainer width="100%" height={220}>
        <LineChart
          data={revenueData}
          margin={{ top: 16, right: 8, left: 0, bottom: 4 }}
          onMouseMove={() => setTooltipActive(true)}
          onMouseLeave={() => setTooltipActive(false)}
        >
          {[100000000, 200000000, 300000000, 400000000, 500000000].map((v) => (
            <ReferenceLine key={v} y={v} stroke="var(--line)" strokeWidth={1} />
          ))}
          <XAxis
            dataKey="month"
            tick={{ fontFamily: "var(--font-geist-mono)", fontSize: 9.5, fill: "var(--muted-2)" }}
            axisLine={false}
            tickLine={false}
            interval={1}
            tickFormatter={(v, i) => i % 2 === 0 ? v : ""}
          />
          <YAxis
            tick={yTick as never}
            axisLine={false}
            tickLine={false}
            domain={[0, 500000000]}
            ticks={[100000000, 200000000, 300000000, 400000000, 500000000]}
            width={42}
          />
          <Tooltip content={<CustomTooltip />} />
          <Line
            type="linear"
            dataKey="revenue"
            stroke={LINE1}
            strokeWidth={1.5}
            dot={false}
            activeDot={{ r: 3.5, fill: LINE1, strokeWidth: 0 }}
          />
          <Line
            type="linear"
            dataKey="adSpend"
            stroke={LINE2}
            strokeWidth={1.5}
            dot={false}
            activeDot={{ r: 3.5, fill: LINE2, strokeWidth: 0 }}
          />
        </LineChart>
      </ResponsiveContainer>
    </CardWrapper>
  );
}
