"use client";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { trafficData, formatVisits } from "@/lib/data";
import CardWrapper from "@/components/CardWrapper";

const TICK_MONTHS = ["Apr", "Jun", "Aug", "Oct", "Dec", "Feb", "Apr"];
const MONTH_INDICES = [0, 4, 8, 12, 16, 20, 24];

function xTick({ x, y, index }: { x: number; y: number; index: number }) {
  const pos = MONTH_INDICES.indexOf(index);
  if (pos === -1) return <g />;
  return (
    <text
      x={x}
      y={y + 12}
      textAnchor="middle"
      fill="var(--muted)"
      style={{ fontFamily: "var(--font-geist-mono)", fontSize: 9.5 }}
    >
      {TICK_MONTHS[pos]}
    </text>
  );
}

function yTick({ x, y, payload }: { x: number; y: number; payload: { value: number } }) {
  return (
    <text
      x={x - 2}
      y={y + 3}
      textAnchor="end"
      fill="var(--muted)"
      style={{ fontFamily: "var(--font-geist-mono)", fontSize: 9.5 }}
    >
      {payload.value === 0 ? "0" : formatVisits(payload.value)}
    </text>
  );
}

function CustomTooltip({ active, payload, label }: { active?: boolean; payload?: { value: number }[]; label?: string }) {
  if (!active || !payload?.length) return null;
  return (
    <div
      style={{
        background: "var(--card)",
        border: "1px solid var(--line)",
        borderRadius: 8,
        padding: "6px 10px",
        fontFamily: "var(--font-geist-mono)",
        fontSize: 11,
        color: "var(--ink)",
        boxShadow: "var(--tooltip-shadow)",
      }}
    >
      <div style={{ color: "var(--muted)", marginBottom: 2 }}>{label}</div>
      <div style={{ fontWeight: 500 }}>{formatVisits(payload[0].value)} visitors</div>
    </div>
  );
}

export default function TrafficCard() {
  return (
    <CardWrapper
      title="Metric name"
      description="One line metric description or function"
      insight="Insight is Autogenerated"
      explanationTitle="Explanation of movement"
      explanationBody="Explains the movement of the graph and pulls out values, no judgment is exerted here."
    >
      <ResponsiveContainer width="100%" height={220}>
        <BarChart data={trafficData} barSize={6} margin={{ top: 4, right: 4, left: 0, bottom: 4 }}>
          <XAxis
            dataKey="week"
            tick={xTick as never}
            axisLine={false}
            tickLine={false}
            interval={0}
          />
          <YAxis
            tick={yTick as never}
            axisLine={false}
            tickLine={false}
            domain={[0, 1000000]}
            ticks={[0, 250000, 500000, 750000, 1000000]}
            width={36}
          />
          <Tooltip content={<CustomTooltip />} cursor={{ fill: "rgba(0,0,0,0.04)" }} />
          <Bar
            dataKey="visits"
            radius={[2, 2, 0, 0]}
            fill="#42a5f5"
          />
        </BarChart>
      </ResponsiveContainer>
    </CardWrapper>
  );
}
